// Package wire holds the on-the-wire and carried-state contract shared by
// the definition side (entity/entdefine) and the caller side
// (entity/entclient). Internal: neither kind authors nor callers see it.
package wire

import (
	"encoding/json"

	"github.com/graphene-ci/temporal-entity/pkg/entity"
)

// Reserved signal/query/command names of the chassis.
const (
	DeleteSignalName     = "entity-delete"
	DescribeQueryName    = "describe"
	SetLabelsCommandName = "entity-set-labels"
)

// CompletedOpsCap bounds the completed-operations dedup cache carried
// across Continue-as-New (article: "bounded result caches prevent history
// bloat", oldest entries evicted).
const CompletedOpsCap = 100

// UpdateArgs is the wire shape of every command update: an
// application-level request id (generated by the client) plus the typed
// request encoded as JSON. The request id is what makes deduplication
// survive Continue-as-New — it lives in the envelope's completed-ops cache.
type UpdateArgs struct {
	RequestID entity.RequestID `json:"requestId"`
	Payload   json.RawMessage  `json:"payload"`
}

// CommandEnvelope is one queued command. Handlers never execute side
// effects; they enqueue envelopes for the main loop to serialize.
type CommandEnvelope struct {
	RequestID entity.RequestID   `json:"requestId"`
	Name      entity.CommandName `json:"name"`
	Payload   json.RawMessage    `json:"payload"`
}

// OpResult is a completed command outcome, cached by application-level
// request id so retried/duplicated requests dedup across Continue-as-New.
type OpResult struct {
	Result json.RawMessage `json:"result,omitempty"`
	Err    string          `json:"err,omitempty"`
}

// Envelope is the compact, resumable state of one entity — exactly what
// the article says to carry across Continue-as-New and nothing more:
// current status, resource configuration (Spec), user state, the
// marked-for-deletion flag, pending commands, and the bounded
// completed-operations cache. Large artifacts (manifests, plans, logs)
// must live in external storage; keep references in State.
type Envelope[Spec, State any] struct {
	Initialized bool         `json:"initialized"`
	Phase       entity.Phase `json:"phase"`

	Spec  Spec  `json:"spec"`
	State State `json:"state"`

	// Labels are the entity's markers — metric-label semantics: small
	// string pairs for selection and grouping, never data. Mirrored to
	// the EntityLabels search attribute as "k=v" values.
	Labels map[string]string `json:"labels,omitempty"`

	MarkedForDeletion bool `json:"markedForDeletion"`

	Pending []CommandEnvelope `json:"pending"`

	Completed      map[entity.RequestID]OpResult `json:"completed"`
	CompletedOrder []entity.RequestID            `json:"completedOrder"`
}

// RecordCompleted stores a command outcome in the bounded dedup cache,
// evicting the oldest entries beyond CompletedOpsCap.
func (e *Envelope[S, T]) RecordCompleted(requestID entity.RequestID, res json.RawMessage, err error) {
	if e.Completed == nil {
		e.Completed = map[entity.RequestID]OpResult{}
	}
	r := OpResult{Result: res}
	if err != nil {
		r.Err = err.Error()
	}
	if _, exists := e.Completed[requestID]; !exists {
		e.CompletedOrder = append(e.CompletedOrder, requestID)
	}
	e.Completed[requestID] = r
	for len(e.CompletedOrder) > CompletedOpsCap {
		oldest := e.CompletedOrder[0]
		e.CompletedOrder = e.CompletedOrder[1:]
		delete(e.Completed, oldest)
	}
}

// Snapshot renders the read-only, by-value view handed to query handlers
// and command validators.
func (e *Envelope[Spec, State]) Snapshot() entity.Snapshot[Spec, State] {
	return entity.Snapshot[Spec, State]{
		Phase:             e.Phase,
		Spec:              e.Spec,
		State:             e.State,
		Labels:            copyLabels(e.Labels),
		PendingCommands:   len(e.Pending),
		MarkedForDeletion: e.MarkedForDeletion,
	}
}

// MergeLabels applies a label patch: empty values delete keys, the rest
// overwrite. Returns whether anything changed.
func (e *Envelope[Spec, State]) MergeLabels(patch map[string]string) bool {
	changed := false
	for k, v := range patch {
		if v == "" {
			if _, ok := e.Labels[k]; ok {
				delete(e.Labels, k)
				changed = true
			}
			continue
		}
		if e.Labels[k] != v {
			if e.Labels == nil {
				e.Labels = map[string]string{}
			}
			e.Labels[k] = v
			changed = true
		}
	}
	return changed
}

func copyLabels(in map[string]string) map[string]string {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}
